dataset: "cifar10" # cifar10, cifar100, svhn, fashion_mnist
cnn_model: "resnet18"
batch_size: 128
epochs: 100
lr: 0.1
optimizer: "hadam" # hadam, sgd, adam

# Hadam optimizer specific settings
hadam:
  order: 2

# SGD optimizer specific settings
sgd:
  momentum: 0.9
  weight_decay: 5e-4

# Adam optimizer specific settings
adam:
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 0

enable_progress_bar: true
mode: "train" # train, download, full